### PR TITLE
Fix behavior when not on lovelace and loaded

### LINKED ISSUE #21: 0.110 & dashboard compatibility & (TypeError: Cannot read property 'lovelace' of null)
Logger: frontend.js.latest.202003181
Source: components/system_log/__init__.py:209
First occurred: 10:40:46 PM (4 occurrences)
Last logged: 10:42:55 PM

https://URL/local/community/lovelace-swipe-navigation/swipe-navigation.js:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null
https://URL/local/community/custom-header/custom-header.js:1:7166 Uncaught TypeError: Cannot read property 'querySelector' of undefined

- url: /local/community/lovelace-swipe-navigation/swipe-navigation.js
   type: js

### PR DESCRIPTION
**Pull request by KTibow**
This fixes the behavior of it when it gets loaded, and Lovelace isn't open. It closes #21.

### CODE REVIEW

**Comment by maykar** [comment]
Thanks for this! Though I would rather this use a mutation observer than a timeout.

I did a quick look, but just in case: is there anything else that was changed besides moving into a function with the hui-root timeout?

**Comment by KTibow** [comment]
No, I un-indented it and put it through another differ:
https://www.diffchecker.com/Ro9tRE3E
I looked through some mutation observer docs to see what it is. Do you have any reccomendations for how to configure it, because I'm kind of new?

**Comment by maykar** [comment]
No worries, I'll work on it as soon as I can. I'm currently taking some time away in a cabin with poor internet, but will mess with it soon.

If you wanted to take a crack at it or just check out some uses of mutation observers working with Lovelace elements, I use them quite a bit in Custom Header ( in the [custom-header.ts](https://github.com/maykar/custom-header/blob/master/src/custom-header.ts), in [observers.js](https://github.com/maykar/custom-header/blob/master/src/observers.js), and in [menu-observers.js](https://github.com/maykar/custom-header/blob/master/src/menu-observers.js) ).

**Comment by maykar** [comment]
Updated to trigger when a new dashboard is loaded, kept your timeout for hui-root. Wanted to post these changes before I lint the file so they're easier to see. Next commit will just be linting/formatting.

**Comment by maykar** [comment]
Going to pull this, but I'm going to try to address one or two of the other issues before actual release

**Comment by KTibow** [comment]
FYI spelling:
<del>`swipeNavigaiton`</del>
`swipeNavigation`
(`it` > `ti`)

**Comment by maykar** [comment]
Had another typo elsewhere so this is fixed in the most recent release as well, thanks.

**Pull request merged**
