### PR TITLE
Add RTL Support

### PR DESCRIPTION
**Pull request by micronen**
On RTL systems, the swipe is in the wrong direction.
I've added the option to reverse the swipe direction by setting RTL to true.
Default if LTR mode to maintain current behavior.

Might be improved, is system wide RTL setting can be used instead of local configuration.

### CODE REVIEW

**Comment by maykar** [comment]
Added detection from home-assistant element. Should auto detect rtl. Haven't tested it yet myself. Let me know if it works alright for you and I'll pull or I'll check it when I get the chance. Thanks for this!

**Comment by maykar** [comment]
Cleanup and added check for tabcontainer direction and if custom header is used with tab direction set to rtl.

**Comment by micronen** [comment]
It Works!
Thanks.

**Comment by maykar** [comment]
No, thank you!

**Pull request merged**
